### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by olafveerman** [climatescope/climatescope.github.io#16]

**Comment by smit1678** [comment]
Fixed via https://github.com/climatescope/climatescope.github.io/commit/7cb889912edcbb4ae88cc4fe29aa97508c5bf458, then https://github.com/climatescope/climatescope.github.io/commit/c94ef9f86b93bb5ba4bf5df104e292d51f369b0b, and then finally https://github.com/climatescope/climatescope.github.io/commit/838189298ffcca17b3162ad464e548c91782539f. Third time is the charm. :shipit:
