### ISSUE TITLE
Site header image not showing Chrome + Windows

### ISSUE THREAD

**Issue by smit1678** [climatescope/climatescope.github.io#23]
Seen on Chrome 46.0.2490.86 + Windows. Header image is not showing up. Issue seems to stem from `background-blend-mode: multiply;` -- [line 277](https://github.com/climatescope/climatescope.github.io/blob/publish/app/assets/styles/_base.scss#L277).

It's been flagged in Chromium and resolved: https://code.google.com/p/chromium/issues/detail?id=543583. Unsure when it will be released into stable channel. 

@danielfdsilva @ricardomestre If Chrome doesn't do a new release tomorrow, suggestions for what we should do to fix? 

![dashboard 2015-11-15 21-54-13](https://cloud.githubusercontent.com/assets/796838/11173364/6e37f446-8be3-11e5-9636-31419613611f.png)

**Comment by danielfdsilva** [comment]
The `background-blend-mode` is an experimental property and should be used with caution. For now I just removed it ensuring that it works. The image is lighter so we should darken it manually and replace it.
